# Clippy configuration

avoid-breaking-exported-api = false
msrv = "1.80.0"

# Warn on common issues
warn = [
    "clippy::all",
    "clippy::pedantic",
    "clippy::nursery",
    "clippy::cargo",
]

# Allow some pedantic lints
allow = [
    "clippy::module_name_repetitions",
    "clippy::must_use_candidate",
    "clippy::missing_errors_doc",
    "clippy::missing_panics_doc",
    "clippy::struct_excessive_bools",
]