# Clippy configuration

avoid-breaking-exported-api = false
msrv = "1.80.0"

# Cognitive complexity threshold
cognitive-complexity-threshold = 20

# Too many arguments threshold
too-many-arguments-threshold = 7

# Large error threshold
large-error-threshold = 128